### ISSUE TITLE
Remove gorilla context and use go context

### ISSUE THREAD

**Issue by devdinu** [gojek-engineering/client-id-auth-middleware#4]
gorilla context.Set(r, key, val) needs to be cleared explicitly if not will cause memory leak.

**Comment by dineshkumar-cse** [comment]
bddbd07672b25b29a7f44a4ac07424ec9d6676b1 closes this issue. removed gorilla context and using golang context to set request id.

**Comment by devdinu** [comment]
bddbd07672b25b29a7f44a4ac07424ec9d6676b1 closes this issue. removed gorilla context and using golang context to set request id.
